version: '3.8'

services: # services are just containers in production
  
  database:
    container_name: database #actual name of the container when it runs
    image: mysql:8.0.29 # mysql version to use
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pw
    ports:
      - '3306:3306'
    volumes:
      - app_db:/var/lib/mysql # where to persist data generated
    networks:
      - symfony

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony # where to place project files
    depends_on:
      - database
    networks:
      - symfony

  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/symfony 
    depends_on:
      - php
      - database
    links:
      - php
    networks:
      - symfony

volumes:
  app_db:

networks:
  symfony: