version: '3.8'

services: # services are just containers in production
  
  # database
  database:
    container_name: database #actual name of the container when it runs
    image: mysql:8.0.29 # mysql version to use
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pw
    ports:
      - '4306:4306'
    volumes:
      - ./.mysql:/var/lib/mysql # where to persist data generated

  # php
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony
    depends_on:
      - database

  # nginx
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database