version: '3.9'

services:
  database:
    container_name: database
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pw
    ports:
      - '3306:3306'
    volumes:
      - app_db:/var/lib/mysql # where to persist data generated
    networks:
      - symfony

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony # where to place project files
    depends_on:
      - database
    networks:
      - symfony

  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/symfony:ro
    depends_on:
      - php
      - database
    links:
      - php
    networks:
      - symfony

  node:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: node
    volumes:
      - ./:/var/www/symfony:rw
    ports:
      - "8080"
    networks:
      - symfony

  cache:
    container_name: redis
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - symfony

volumes:
  app_db:
  cache:
    driver: local

networks:
  symfony: